version: '3.1'

services:
  mysql:
    container_name: larambla-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'larambla'
      MYSQL_USER: 'larambla'
      MYSQL_PASS: 'larambla'
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_CREATE_TOPICS: 'larambla-member:1:1'
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
