server:
  forward-headers-strategy: FRAMEWORK
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT:5000}

spring:
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: